### PR TITLE
Gary's 1/28 homework (draft)

### PR DESCRIPTION
**Pull request by garywmendel**

### CODE REVIEW

**Comment by justmarkham** [comment]
Hi Gary, this is looking good! Since you marked this as draft, I'll wait until after Wednesday and see if you make any other changes, and then give you detailed feedback. If you want me to go ahead and review now, just let me know and I can do it.

(Side note: If you commit and push up new changes before I merge your pull request, they will automatically be incorporated into the existing pull request... you won't have to create a new pull request. Just an FYI!)

**Comment by justmarkham** [comment]
Hi @garywmendel, sorry I haven't yet had time to review this. Just wanted to let you know I'll get to it soon, probably tonight or Saturday morning. Thanks!

**Comment by garywmendel** [comment]
i haven’t updated it since last time.  will work on this weekend.

**Comment by justmarkham** [comment]
Hi @garywmendel, I took a read through what you've got so far. If I recall correctly, Sinan was able to help you turn my sample code into something that reads through the entire CSV -- that's great! I would recommend saving that piece of code in the repo so that when you figure out additional features that you need to extract from each poll, we can simply enhance that code rather than starting from scratch.

The week of 2/9, we will be covering how to extract features from text (in the context of Naive Bayes classification), as well as NLP in general, which should be helpful for your project.

As we talked about in class, I think it's best to narrow your focus to one (or maybe two) questions so that you have the time to make significant progress on that question, rather than spreading your efforts too thin across multiple questions.

Finally, it would be great to hear what you learn from the exploratory process. Feel free to push up more code and writeups at any time, and I can continue to give you feedback.

Good job!

**Comment by garywmendel** [comment]
hi kevin, i am going to focus on the question "Yopine - What are the natural content 'Categories' that have been created via app usage as arrived at scientifically using data from the 'Poll' table (contains 'Brainstorm' data as well)".  

I will save the final two (and likely others for independent post-DAT4 class projects) as ways to keep what i learned moving forward as i strive to improve my weakness which is the code.  my goal is to be able to do, basically, any type of DS analysis using DAT4 as the knowledge basis.

my next steps here are to pick which models i will be using.  last class taught me that train test split and confusion matrices will get me headed in the right direction...ie scoring what should even be in the realm of possibility.

from there, the more interesting and useful stuff will be the parsing of the text fields (pollQuestion, pollAnswer, pollComments, pollTags) to extract features (Naive Bayes).

i am in Cincinnati this sunday to wed so i will miss monday class but will pick it up on video.  i hope to be at wed, but that depends on weather, flights etc.  currently i should be back in time to make it.

i will need help getting the code syntax right to do what im trying to do but i have pretty specific goals and pretty sure i understand how to decide which methods are the right ones.

thanks for all the help.

**Comment by justmarkham** [comment]
All sounds good @garywmendel, thanks for the detailed updates!

Good luck with your trip.

**Pull request merged**
